package store

import (
	"context"
	"log/slog"
)

// schemaStatements reproduce the idempotent ensure_*_schema() DDL from the PHP
// entrypoints (db_api.php, room_api.php, library_api.php, lib/RateLimit.php).
// Each statement is executed independently and errors are logged, matching the
// per-statement try/catch behaviour of the originals.
var schemaStatements = []string{
	`CREATE TABLE IF NOT EXISTS users (
		id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		email VARCHAR(255) NOT NULL UNIQUE,
		password VARCHAR(255) NOT NULL,
		user_uuid VARCHAR(64) NOT NULL UNIQUE,
		auth_token VARCHAR(128) NULL,
		role VARCHAR(16) NOT NULL DEFAULT 'user',
		banned BOOLEAN NOT NULL DEFAULT FALSE,
		created_at TIMESTAMP NOT NULL DEFAULT NOW()
	)`,
	`ALTER TABLE users ADD COLUMN IF NOT EXISTS role VARCHAR(16) NOT NULL DEFAULT 'user'`,
	`ALTER TABLE users ADD COLUMN IF NOT EXISTS banned BOOLEAN NOT NULL DEFAULT FALSE`,
	`CREATE TABLE IF NOT EXISTS user_data (
		user_id VARCHAR(64) NOT NULL,
		settings TEXT NULL,
		investigators TEXT NULL,
		saves TEXT NULL,
		tavern_novels TEXT NULL,
		revision BIGINT NOT NULL DEFAULT 0,
		updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
		PRIMARY KEY (user_id)
	)`,
	`CREATE TABLE IF NOT EXISTS coc_rooms (
		room_id VARCHAR(32) NOT NULL,
		host_id VARCHAR(64) NOT NULL,
		host_token_hash CHAR(64) NULL,
		is_public BOOLEAN NOT NULL DEFAULT FALSE,
		name VARCHAR(120) NULL,
		created_at TIMESTAMP NOT NULL DEFAULT NOW(),
		updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
		PRIMARY KEY (room_id)
	)`,
	`ALTER TABLE coc_rooms ADD COLUMN IF NOT EXISTS is_public BOOLEAN NOT NULL DEFAULT FALSE`,
	`ALTER TABLE coc_rooms ADD COLUMN IF NOT EXISTS name VARCHAR(120) NULL`,
	`CREATE INDEX IF NOT EXISTS idx_updated_at ON coc_rooms (updated_at)`,
	`CREATE TABLE IF NOT EXISTS coc_room_messages (
		id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		room_id VARCHAR(32) NOT NULL,
		sender_id VARCHAR(64) NOT NULL,
		payload TEXT NOT NULL,
		created_at TIMESTAMP NOT NULL DEFAULT NOW()
	)`,
	`CREATE INDEX IF NOT EXISTS idx_room_id_id ON coc_room_messages (room_id, id)`,
	`CREATE INDEX IF NOT EXISTS idx_created_at ON coc_room_messages (created_at)`,
	`CREATE TABLE IF NOT EXISTS coc_room_presence (
		room_id VARCHAR(32) NOT NULL,
		user_id VARCHAR(64) NOT NULL,
		last_seen TIMESTAMP NOT NULL DEFAULT NOW(),
		PRIMARY KEY (room_id, user_id)
	)`,
	`CREATE TABLE IF NOT EXISTS coc_library_modules (
		id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		created_at TIMESTAMP NOT NULL DEFAULT NOW(),
		title VARCHAR(255) NOT NULL,
		description TEXT NULL,
		content TEXT NOT NULL,
		author_name VARCHAR(120) NULL,
		author_id VARCHAR(64) NOT NULL,
		owner_token_hash CHAR(64) NOT NULL,
		type VARCHAR(32) NOT NULL DEFAULT 'original',
		downloads BIGINT NOT NULL DEFAULT 0,
		min_players INTEGER NULL,
		max_players INTEGER NULL
	)`,
	`CREATE INDEX IF NOT EXISTS idx_type_created ON coc_library_modules (type, created_at)`,
	`CREATE INDEX IF NOT EXISTS idx_author_id ON coc_library_modules (author_id)`,
	`CREATE TABLE IF NOT EXISTS coc_friendships (
		user_a VARCHAR(64) NOT NULL,
		user_b VARCHAR(64) NOT NULL,
		created_at TIMESTAMP NOT NULL DEFAULT NOW(),
		PRIMARY KEY (user_a, user_b)
	)`,
	`CREATE INDEX IF NOT EXISTS idx_coc_friendships_b ON coc_friendships (user_b)`,
	`CREATE TABLE IF NOT EXISTS coc_friend_requests (
		id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		from_uuid VARCHAR(64) NOT NULL,
		to_uuid VARCHAR(64) NOT NULL,
		status VARCHAR(16) NOT NULL DEFAULT 'pending',
		created_at TIMESTAMP NOT NULL DEFAULT NOW(),
		updated_at TIMESTAMP NOT NULL DEFAULT NOW()
	)`,
	`CREATE UNIQUE INDEX IF NOT EXISTS idx_coc_friend_requests_pending ON coc_friend_requests (from_uuid, to_uuid) WHERE status = 'pending'`,
	`CREATE INDEX IF NOT EXISTS idx_coc_friend_requests_to ON coc_friend_requests (to_uuid, status)`,
	`CREATE TABLE IF NOT EXISTS coc_user_presence (
		user_uuid VARCHAR(64) NOT NULL PRIMARY KEY,
		last_seen TIMESTAMP NOT NULL DEFAULT NOW()
	)`,
	`CREATE TABLE IF NOT EXISTS coc_friend_invites (
		id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		from_uuid VARCHAR(64) NOT NULL,
		to_uuid VARCHAR(64) NOT NULL,
		room_id VARCHAR(32) NOT NULL,
		status VARCHAR(16) NOT NULL DEFAULT 'pending',
		created_at TIMESTAMP NOT NULL DEFAULT NOW(),
		updated_at TIMESTAMP NOT NULL DEFAULT NOW()
	)`,
	`CREATE INDEX IF NOT EXISTS idx_coc_friend_invites_to ON coc_friend_invites (to_uuid, status)`,
	`CREATE TABLE IF NOT EXISTS coc_admin_audit (
		id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		admin_uuid VARCHAR(64) NOT NULL,
		action VARCHAR(64) NOT NULL,
		target VARCHAR(128) NULL,
		detail TEXT NULL,
		ip VARCHAR(45) NULL,
		created_at TIMESTAMP NOT NULL DEFAULT NOW()
	)`,
	`CREATE INDEX IF NOT EXISTS idx_coc_admin_audit_created ON coc_admin_audit (created_at DESC)`,
}

// EnsureSchema creates every table/index if missing. It is safe to call once at
// startup (the PHP side runs these through app_run_periodically()).
func EnsureSchema(ctx context.Context, s *Store, logger *slog.Logger) {
	for _, stmt := range schemaStatements {
		if _, err := s.Pool.Exec(ctx, stmt); err != nil {
			logger.Warn("schema statement failed", "error", err, "sql", stmt)
		}
	}
}
